;;;; im.asd
;;;;
;;;; Five systems, down from the twelve .asd files this repository used to
;;;; carry at its root (im, im-cffi, im-all, im-process, im-process-cffi,
;;;; im-jp2, im-jp2-cffi, im-avi, im-avi-cffi, im-wmv, im-wmv-cffi,
;;;; im-capture, im-capture-cffi, im-examples, im-tests).
;;;;
;;;; That layout paired every feature area with a separate -cffi system. The
;;;; split is worth keeping as a rule about files -- src/ffi/ is drafted by a
;;;; generator and hand-corrected, src/ is written by hand -- but as a rule
;;;; about systems it bought nothing: nothing ever depended on a -cffi system
;;;; without also depending on its wrapper.

(defsystem #:im
  :description "Common Lisp bindings to IM, Tecgraf's image toolkit."
  :author "Matthew Kennedy <burnsidemk@gmail.com>"
  :homepage "https://github.com/lispnik/im"
  :licence "MIT"
  :version (:read-file-line "version.txt")
  :serial t
  :pathname "src"
  :components ((:file "package")
               (:file "conditions")
               (:file "library")
               ;; Hand-written FFI pieces live here rather than in src/ffi/,
               ;; which tools/gen-bindings.lisp owns and clears on every run.
               (:file "ffi-structs")
               ;; Generated by tools/gen-bindings.lisp and then hand-corrected.
               ;; types.lisp must come first: it defines the opaque handle
               ;; types every other file's signatures are written in terms of.
               (:module "ffi"
                :serial t
                :components ((:file "types")
                             (:file "im-lib")
                             (:file "im-file")
                             (:file "im-image")
                             (:file "im-palette")
                             (:file "im-convert")
                             (:file "im-counter")
                             (:file "im-util")
                             (:file "im-binfile")
                             (:file "im-kernel")
                             (:file "im-attrib")
                             (:file "im-color")
                             (:file "im-old")
                             (:file "im-capture")
                             (:file "im-format-addon")
                             (:file "im-process-pnt")
                             (:file "im-process-loc")
                             (:file "im-process-glo")
                             (:file "im-process-ana")
                             (:file "manifest")))
               (:file "image")
               (:file "counter")
               (:file "file")
               ;; After file.lisp: DISPLAY writes the image out with SAVE.
               (:file "display")
               (:file "process")
               (:file "capture"))
  :depends-on (#:cffi
               #:alexandria
               #:trivial-garbage)
  :in-order-to ((test-op (test-op #:im/tests))))

(defsystem #:im/cli
  :description "im(1), a command-line driver for the IM bindings."
  :author "Matthew Kennedy <burnsidemk@gmail.com>"
  :licence "MIT"
  :version (:read-file-line "version.txt")
  :serial t
  ;; The components sit in a module rather than under a system-level
  ;; :PATHNAME, because ASDF resolves :BUILD-PATHNAME against the system's
  ;; pathname: with :pathname "src/cli" the binary is written to
  ;; src/cli/bin/im, not to bin/im.
  :components ((:module "cli"
                :pathname "src/cli"
                :serial t
                :components ((:file "package")
                             (:file "output")
                             (:file "main")
                             ;; One file per subcommand group. Each registers
                             ;; itself at load time and MAIN reads the registry
                             ;; at startup, so this order does not decide the
                             ;; order in --help.
                             (:file "info")
                             (:file "convert")
                             (:file "process")
                             (:file "analyze")
                             (:file "stats")
                             (:file "capture"))))
  :depends-on (#:im #:clingon #:shasht #:alexandria)
  :build-operation "program-op"
  :build-pathname "bin/im"
  :entry-point "im.cli:main")

;; Halves the shipped binary. SBCL builds without core compression exist, so
;; this is conditional rather than a :COMPRESSION entry in the defsystem.
#+sb-core-compression
(defmethod asdf:perform ((o asdf:image-op) (c asdf:system))
  (uiop:dump-image (asdf:output-file o c) :executable t :compression t))

(defsystem #:im/tests
  :description "FiveAM suite for the IM bindings."
  :author "Matthew Kennedy <burnsidemk@gmail.com>"
  :licence "MIT"
  :serial t
  :pathname "tests"
  :components ((:file "package")
               (:file "library")
               (:file "image")
               (:file "file")
               (:file "conditions")
               (:file "display")
               (:file "process")
               (:file "cli"))
  ;; im/cli as well as im: the suite drives bin/im as a subprocess, and also
  ;; checks a couple of the CLI's own functions directly, which needs the
  ;; package to exist at compile time.
  :depends-on (#:im #:im/cli #:fiveam #:trivial-garbage #:shasht)
  ;; FiveAM's RUN! prints its report and returns NIL when anything failed.
  ;; Discarding that value makes TEST-OP succeed on a failing suite, which is
  ;; how this project's CI once went green with three tests failing.
  :perform (test-op (op c)
                    (unless (uiop:symbol-call :fiveam :run!
                                              (uiop:find-symbol* :im-suite :im.tests))
                      (cl:error "The IM test suite failed."))))
